image: rust:latest

stages:
  - build
  - test
  - release

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"
  CARGO_TARGET_DIR: "${CI_PROJECT_DIR}/target"
  # Cache dependencies between builds
  CARGO_INCREMENTAL: 0
  # Use thin LTO for linking
  CARGO_PROFILE_RELEASE_LTO: "thin"

.rust-cache:
  cache:
    key:
      files:
        - Cargo.lock
    paths:
      - .cargo/
      - target/

build:
  stage: build
  extends: .rust-cache
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings
    - rustup component add rustfmt
    - cargo fmt -- --check
    - rustup target add x86_64-unknown-linux-gnu
    - cargo build --target x86_64-unknown-linux-gnu

test:
  stage: test
  extends: .rust-cache
  needs:
    - build
  script:
    - cargo test --verbose

release:
  stage: release
  extends: .rust-cache
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - add-apt-repository universe
    - apt-get update
    - apt-get install jq -y
    - apt-get install curl -y
  script:
    - rustup target add x86_64-unknown-linux-gnu
    - cargo build --release --target x86_64-unknown-linux-gnu
    - mkdir -p artifacts
    - tar -czvf hoi-linux-x86_64.tar.gz target/x86_64-unknown-linux-gnu/release/hoi
    - mv hoi-linux-x86_64.tar.gz $CI_PROJECT_DIR/artifacts/hoi-linux-x86_64.tar.gz
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
           --upload-file $CI_PROJECT_DIR/artifacts/hoi-linux-x86_64.tar.gz \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/hoi/${CI_COMMIT_TAG}/hoi-linux-x86_64.tar.gz"
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --data tag_name="${CI_COMMIT_TAG}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases"
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" -F "file=@$CI_PROJECT_DIR/artifacts/hoi-linux-x86_64.tar.gz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/uploads" | 
      jq -r '.url' | 
      xargs -I{} curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --request POST "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/${CI_COMMIT_TAG}/assets/links" --data "name=hoi-linux-x86_64.tar.gz" --data "url={}"