[package]
name = "hoi"
version = "0.7.2"
edition = "2021"
authors = ["Kevin Quillen <kevinquillen@gmail.com>"]
description = "Cross-platform command runner for development teams. Define project tasks in .hoi.yml and run them with a single command."
readme = "README.md"
license = "MIT"
keywords = ["command-runner", "task-runner", "yaml", "cli", "development-tools"]
categories = ["command-line-utilities", "development-tools"]
documentation = "https://github.com/kevinquillen/hoi#usage"
homepage = "https://github.com/kevinquillen/hoi"
repository = "https://github.com/kevinquillen/hoi"
exclude = [".github/"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml_ng = "0.10"
tabled = "0.18.0"
thiserror = "2.0.12"
dirs = "6"
indexmap = { version = "2.0", features = ["serde"] }
rand = "0.8.5"
dotenvy = "0.15.7"

[dev-dependencies]
temp-env = "0.3"
testdir = "0.9"
utilities = { path = "utilities" }
