[package]
name = "hoi"
version = "0.1.0"
edition = "2021"
authors = ["Kevin Quillen <kevin.quillen@velir.com>"]
description = "hoi is a command-line tool to help create simple command-line powered utilities."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"